### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by thorstenman** [zerwuff/homebridge-alphaess#1]
**Describe The Bug:**
Everything worked fine. Not sure, when it broke. Tried to (re)connect but seeing the error message below.

MQTT is not in use so far. I even left out the relate attributes during plugin config.

**To Reproduce:**
Reinstall, reconfigure.

**Expected behavior:**
Successful connection, device to show up in HomeKit.

**Logs:**

```
[2/15/2023, 1:29:44 AM] ====================
[2/15/2023, 1:29:44 AM] ERROR LOADING PLUGIN homebridge-alphaess:
[2/15/2023, 1:29:44 AM] Error: Cannot find module 'mqtt'
Require stack:
- /var/lib/homebridge/node_modules/homebridge-alphaess/dist/AlphaTriggerPlugin.js
- /var/lib/homebridge/node_modules/homebridge-alphaess/dist/index.js
- /var/lib/homebridge/node_modules/homebridge/lib/plugin.js
- /var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js
- /var/lib/homebridge/node_modules/homebridge/lib/server.js
- /var/lib/homebridge/node_modules/homebridge/lib/cli.js
- /var/lib/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/src/AlphaTriggerPlugin.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
```

```
No plugin was found for the platform "AlphaEssPlatform" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

**Plugin Config:**

```json

        {
            "username": "xxx",
            "password": "xxx",
            "serialnumber": "ALB002xxx",
            "powerLoadingThreshold": 1500,
            "socLoadingThreshold": 50,
            "refreshTimerInterval": 60000,
            "logrequestdata": false,
            "platform": "AlphaEssPlatform"
        }
```

**Environment:**

* **Plugin Version**: 2.14.0
* **Homebridge Version**: 450.2
* **Node.js Version**: 9.4.2
* **NPM Version**: 18.13.1
* **Operating System**: Raspbian Buster

**Comment by zerwuff** [comment]
Hi Thorsten, thanks for your feedback - sorry for this trouble. i will fix this issue in the next minor release. for a quick workaround use 
`npm install -g mqtt ` to add the mqtt package to your local npm repository.

**Comment by zerwuff** [comment]
fixed with v2.15.0. Please update and, feedback + close this issue is appreciated

**Comment by thorstenman** [comment]
Awesome, it works now. Thank you so much! 

Do you habe plans to further extend functionality? I still have problems to control surplus PV power in more detail in combination with my wallbox. 

Hope to find a workaround via other platforms like EVCC, HA or IOBroker - but was not able to succeed so far.

**Comment by zerwuff** [comment]
no problem. i close this bug for now.

im planning to extend the project, which platform would be most fitting ? IOBroker ? If you could write a small feature request with good details i'll check this and me might make this work with your setup. 
BG, Jens

**Comment by thorstenman** [comment]
Hi Jens, thanks for your offer. I learned a lot in the last days... need to further investigate and think about potential use cases on basis of homebridge. Since I revealed some gaps in APIs I use (AlphaESS PV, myEnergi Zappi wallbox) and combine this with HomeKit capabilities, I'd rather say that I need to invest more effort in IOBroker instead.
