### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by CharlieVD** [zerwuff/homebridge-alphaess#14]
AlphaESS native app can show other params like “Feed-in”, ”Load”. Can You add it to plugin, or it is not possible?

**Comment by zerwuff** [comment]
@CharlieVD  should be working now. 

Load: (w) Is the Load (W) to the system
Feed-In : (w) Is negative when feeding into the net, and positive when fetching from the net.

**Comment by CharlieVD** [comment]
Added. Thanks
