### ISSUE TITLE
Enable battery discharge with simple switch in HomeKit

### ISSUE THREAD

**Issue by DobbyNator94** [zerwuff/homebridge-alphaess#19]
**Is your feature request related to a problem? Please describe:**
Would be great if I discover a big device that consumes e.g. over 2KW, that it automatically stops to discharge the AlphaESS battery.

**Describe the solution you'd like:**
A simple switch in HomeKit that enables / disables the battery discharge. With an automation in HomeKit and the other values from the HomeBridge plugin I can simply control the discharge of the Battery.

**Comment by DobbyNator94** [comment]
Or a setting in the plugin (json) would be even easier. If a usage of grid power or general consumption is over a certain limit, disable battery discharge. Maybe a setting for time intervall for checking if the power usage is below the setting to turn battery discharge on again.

Because of an oven or a water heater or stuff like that. 30 minutes showering and the battery is at 4% on my 8KWh battery pack.

**Comment by zerwuff** [comment]
The API call to build this feature is limited to once a day. Also, the api only allows to prevent discharging during fixed time hours. What i could do is to build the following:

Add new parameters for your stop discharge feature: 
 * limit of watts which triggers the feature (W) , 
 * time in minutes (m) the discharging should be stopped.
 
After detecting a peak of *W* watts, stop discharging the alpha for *m* minutes. 
Would this be sufficient for you, triggerd a maximu once per day ?

**Comment by DobbyNator94** [comment]
When its only possible for once a day, thats not enough. Maybe I set the dishwasher or shower, at different hours. Than it is only possible to dissable discharge for 1 event a day?

**Comment by zerwuff** [comment]
As per API limitation by Alpha ESS, yes.
