### ISSUE TITLE
Last update does not work - does not show any values

### ISSUE THREAD

**Issue by CharlieVD** [zerwuff/homebridge-alphaess#21]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Please enable Debug Mode (-D)  in Homebridge to see more details about the homebridge-alphaess plugin  
Show the Homebridge logs here, remove any sensitive information.

```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by zerwuff** [comment]
The alpha ess openapi seems to be broken, probably in correlation with the latest big update. There is currently nothing to be fixed on the plugin side.  All consumers of the openapi are affected

**Comment by zerwuff** [comment]
see https://github.com/alphaess-developer/alphacloud_open_api/issues/88 and https://github.com/alphaess-developer/alphacloud_open_api/issues/89

**Comment by CharlieVD** [comment]
Hi,

 

It looks that migration on new server is finished and app work properly.

Unfortunately still not getting values from plugin.

**Comment by zerwuff** [comment]
Seems like Alpha has fixed this. I close your issue now.
