### ISSUE TITLE
Could not login to Alpha Cloud, please check username or password

### ISSUE THREAD

**Issue by mschorf** [zerwuff/homebridge-alphaess#5]
**Describe Your Problem:**

Just installed the plugin for my new ESS - get the folowing error in Homebridge: 

[11/4/2023, 4:10:59 PM] [AlphaEssPlatform] Could not login to Alpha Cloud, please check username or password
[11/4/2023, 4:10:59 PM] [AlphaEssPlatform] Could not login to Alpha Cloud, please check username or password

I checked Username and Passwort a few times - they are correct and I can use it to login tio the alpha cloud in the App / Web.

Maybe because Username hs @ in it and Passwort has ! in it ?

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

"username": "xxxx@xxxxx.at",
            "password": "XXXxxxxxx!xx",
            "serialnumber": "ALB002xxxxxxxxxx",
            "powerLoadingThreshold": 1500,
            "socLoadingThreshold": 50,
            "refreshTimerInterval": 60000,
            "power_image_filename": "/tmp/alpha_power_image.png",
            "logrequestdata": false,
            "tibberEnabled": false,
            "tibberLoadBatteryEnabled": false,
            "tibberLoadingMinutes": 60,
            "tibberThresholdSOC": 60,
            "tibberThresholdEur": 0.01,
            "triggerImageFilename": "/tmp/tibber_image.png",
            "platform": "AlphaEssPlatform"

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by zerwuff** [comment]
Hi, 

Alpha changed their API Endpoint yesterday. Please Update to latest version and add  

    "alphaUrl": "https://www.alphaess-cloud.com/api"

to your config.  That should get back the plugin to work
