### ISSUE TITLE
get amount of solar power

### ISSUE THREAD

**Issue by akassa89** [zerwuff/homebridge-alphaess#8]
Hi everyone,

i need this as LUX indicator to automate some switches in HomeKit.
Ex: if solar power >2000 LUX (W is meant) than turn on IR-heating 

thx for your help

**Comment by zerwuff** [comment]
nice idea, will implement it when having time in the next weeks.

**Comment by zerwuff** [comment]
hi @akassa89 new lux sensor was added in v 2.86
