### ISSUE TITLE
"Video" preview shows actual data but when opening the video, a different view appears

### ISSUE THREAD

**Issue by wuedan** [zerwuff/homebridge-alphaess#9]
**Describe The Bug:**
I was using this Plugin previously on my Mac installation of Homebridge, however due to ongoing issues, I now installed home bridge on a separate raspberry.
I setup homebridge and installed the AlphaESS Plugin as well as Homebridge Camera FFMPeg, there are no other plugins installed.
When I now preview the camera feed, it shows todays graphs.
When I then open the feed to have a bigger view, I get an outdated view.

Additionally I set up a notification for the Trigger to have the Home-App send me a notification once the trigger fires.. This notification only gets send when I login to home bridge or open the home app.

**To Reproduce:**
Open Home App and click on the Video Preview.

**Expected behavior:**
Actual Live view to show same info as preview screen did.

**Logs:**

```
[23/03/2024, 15:53:51] [Camera FFmpeg] [AlphaESS] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[23/03/2024, 15:53:54] [Camera FFmpeg] [AlphaESS] Stopped video stream.
[23/03/2024, 15:54:31] [Camera FFmpeg] [AlphaESS] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[23/03/2024, 15:54:46] [Camera FFmpeg] [AlphaESS] Stopped video stream.
[23/03/2024, 16:07:48] [Camera FFmpeg] [AlphaESS] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[23/03/2024, 16:07:51] [Camera FFmpeg] [AlphaESS] Stopped video stream.
```

**Plugin Config:**

```
{
            "alphaUrl": "https://openapi.alphaess.com/api",
            "appid": "xxx",
            "appsecret": "xxx",
            "serialnumber": "xxx",
            "powerLoadingThreshold": 1500,
            "socLoadingThreshold": 100,
            "refreshTimerInterval": 60000,
            "power_image_filename": "/home/homebridge/alpha_power_image.png",
            "logrequestdata": false,
            "tibberEnabled": false,
            "tibberLoadBatteryEnabled": false,
            "tibberLoadingMinutes": 60,
            "tibberThresholdSOC": 60,
            "tibberThresholdEur": 0.01,
            "triggerImageFilename": "/home/homebridge/tibber_image.png",
            "platform": "AlphaEssPlatform"
        },
        {
            "name": "Camera FFmpeg",
            "videoProcessor": "/usr/bin/ffmpeg",
            "cameras": [
                {
                    "name": "AlphaESS",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-f image2 -loop 1 -s 640x360 -pix_fmt yuvj422p -i /tmp/alpha_power_image.png",
                        "stillImageSource": "-i file:///home/homebridge/alpha_power_image.png",
                        "audio": false
                    }
                },
                {
                    "name": "Trigger",
                    "unbridge": false,
                    "videoConfig": {
                        "source": "-f image2 -loop 1 -s 640x360 -pix_fmt yuvj422p -i /tmp/tibber_image.png",
                        "stillImageSource": "-i file:///home/homebridge/tibber_image.png",
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```
**Screenshots:**
**Preview:**
<img width="105" alt="Screenshot 2024-03-23 15-54-26" src="https://github.com/zerwuff/homebridge-alphaess/assets/79700665/a44c4ec1-4b63-4a65-b73d-2b8288c61aee">

**Live-Feed:**
<img width="508" alt="Screenshot 2024-03-23 15-54-39" src="https://github.com/zerwuff/homebridge-alphaess/assets/79700665/f2243e46-7f11-4a6e-9c74-bf94e41d9c28">

**Notification setting**
<img width="186" alt="Screenshot 2024-03-23 16-10-00" src="https://github.com/zerwuff/homebridge-alphaess/assets/79700665/48d2c381-aab5-4676-984b-0c6f03c736f5">

**Environment:**

* **Plugin Version**: v2.83.0
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.11.1
* **NPM Version**: ?
* **Operating System**: Raspbian Bookworm (12)

**Comment by zerwuff** [comment]
hi, as the homebridges plugin only creates a fixed .png file, the rendering / video preview task on your ios device is handled by the homebridge-camera-ffmpeg plugin.  

Please check if there is already an issue there or create a new https://github.com/Sunoo/homebridge-camera-ffmpeg
